module.exports = {
  getDashboardStats: require("./adminController/getDashboardStats"),
  getModerationDocuments: require("./adminController/getModerationDocuments"),
  reviewDocument: require("./adminController/reviewDocument"),
  viewModerationDocument: require("./adminController/viewModerationDocument"),
  getUsers: require("./adminController/getUsers"),
  updateUserStatus: require("./adminController/updateUserStatus"),
  getActivityLogs: require("./adminController/getActivityLogs"),
  getUsage: require("./adminController/getUsage"),
  updateUserRole: require("./adminController/updateUserRole"),
  getDeletedWorkspaces: require("./adminController/getDeletedWorkspaces"),
  restoreWorkspace: require("./adminController/restoreWorkspace"),
  getWorkspacePurgePreview: require("./adminController/getWorkspacePurgePreview"),
  permanentlyDeleteWorkspace: require("./adminController/permanentlyDeleteWorkspace"),
};
