module.exports = {
  googleLogin: require("./authController/googleLogin"),
  verifyOTP: require("./authController/verifyOTP"),
  checkUsername: require("./authController/checkUsername"),
  completeSetup: require("./authController/completeSetup"),
  login: require("./authController/login"),
  forgotPassword: require("./authController/forgotPassword"),
  verifyResetPasswordOTP: require("./authController/verifyResetPasswordOTP"),
  resetPassword: require("./authController/resetPassword"),
  changePassword: require("./authController/changePassword"),
  deleteAccount: require("./authController/deleteAccount"),
  searchUsers: require("./authController/searchUsers"),
  getUserProfileById: require("./authController/getUserProfileById"),
  refresh: require("./authController/refresh"),
  logout: require("./authController/logout"),
};
