module.exports = {
  listMyDocuments: require("./documentController/listMyDocuments"),
  getMyLibraryStorageUsage: require("./documentController/getMyLibraryStorageUsage"),
  uploadDocuments: require("./documentController/uploadDocuments"),
  suggestDocumentTags: require("./documentController/suggestDocumentTags"),
  downloadDocument: require("./documentController/downloadDocument"),
  viewDocument: require("./documentController/viewDocument"),
  deleteDocument: require("./documentController/deleteDocument"),
  createLibrary: require("./documentController/createLibrary"),
  updateLibrary: require("./documentController/updateLibrary"),
  listMyLibraries: require("./documentController/listMyLibraries"),
  getLibrary: require("./documentController/getLibrary"),
  toggleLibraryStar: require("./documentController/toggleLibraryStar"),
  getLibraryEngagement: require("./documentController/getLibraryEngagement"),
  deleteLibrary: require("./documentController/deleteLibrary"),
  toggleStarLibrary: require("./documentController/toggleStarLibrary"),
};
